{
    "outputDir": "output",
    "StrategyName": "AlgoShaolin",
    "TradingUnderlyingCode": [
                            ["000002.SZ"], 
                            ["000028.SZ"], 
                            ["000063.SZ"], 
                            ["000333.SZ"], 
                            ["000400.SZ"], 
                            ["000530.SZ"], 
                            ["000568.SZ"], 
                            ["000571.SZ"], 
                            ["000581.SZ"], 
                            ["000651.SZ"], 
                            ["000786.SZ"], 
                            ["000826.SZ"], 
                            ["000858.SZ"], 
                            ["000895.SZ"], 
                            ["000910.SZ"], 
                            ["000977.SZ"], 
                            ["001979.SZ"], 
                            ["002008.SZ"], 
                            ["002033.SZ"], 
                            ["002043.SZ"], 
                            ["002128.SZ"], 
                            ["002179.SZ"], 
                            ["002185.SZ"], 
                            ["002236.SZ"], 
                            ["002241.SZ"], 
                            ["002267.SZ"], 
                            ["002294.SZ"], 
                            ["002299.SZ"], 
                            ["002304.SZ"], 
                            ["002311.SZ"], 
                            ["002384.SZ"], 
                            ["002396.SZ"], 
                            ["002456.SZ"], 
                            ["002466.SZ"], 
                            ["002475.SZ"], 
                            ["002508.SZ"], 
                            ["002572.SZ"], 
                            ["002589.SZ"], 
                            ["002594.SZ"], 
                            ["002624.SZ"], 
                            ["002672.SZ"], 
                            ["300015.SZ"], 
                            ["300070.SZ"], 
                            ["300115.SZ"], 
                            ["300197.SZ"], 
                            ["300323.SZ"], 
                            ["300408.SZ"], 
                            ["300418.SZ"], 
                            ["300477.SZ"], 
                            ["600004.SH"], 
                            ["600009.SH"], 
                            ["600029.SH"], 
                            ["600036.SH"], 
                            ["600057.SH"], 
                            ["600110.SH"], 
                            ["600201.SH"], 
                            ["600219.SH"], 
                            ["600236.SH"], 
                            ["600276.SH"], 
                            ["600418.SH"], 
                            ["600498.SH"], 
                            ["600521.SH"], 
                            ["600570.SH"], 
                            ["600589.SH"], 
                            ["600703.SH"], 
                            ["600782.SH"], 
                            ["600805.SH"], 
                            ["600867.SH"], 
                            ["601012.SH"], 
                            ["601021.SH"], 
                            ["601088.SH"], 
                            ["601288.SH"], 
                            ["601318.SH"], 
                            ["601398.SH"], 
                            ["601601.SH"], 
                            ["601939.SH"], 
                            ["601988.SH"], 
                            ["603108.SH"], 
                            ["002056.SZ"], 
                            ["600516.SH"], 
                            ["600362.SH"], 
                            ["600549.SH"], 
                            ["600176.SH"], 
                            ["600519.SH"]
                            ],
    "FactorUnderlyingCode": [],
    "StartDateTime": 20170615093000,
    "EndDateTime": 20180615145659,
    "FactorSet":
        [
            {"name": "factorVolumeMagnification", "className": "FactorVolumeMagnification",
             "indexTradingUnderlying": [0],
             "indexFactorUnderlying": [], "paraFastLag": 10, "paraSlowLag": null, "save": true},

            {"name": "factorPriceChangeRatio", "className": "FactorPriceChangeRatio",
             "indexTradingUnderlying": [0], "indexFactorUnderlying": [], "paraFastLag": 10, "paraSlowLag": 20,
             "save": true},

            {"name": "factorPriceChangeSpeed", "className": "FactorPriceChangeSpeed",
             "indexTradingUnderlying": [0], "indexFactorUnderlying": [], "paraFastLag": 10, "paraSlowLag": 20,
             "save": true},

            {"name": "factorSpeed", "className": "FactorSpeed", "indexTradingUnderlying": [0],
             "indexFactorUnderlying": [],
             "paraLag": 10.0, "paraEmaMidPriceLag": 4, "save": true},

            {"name": "factorEmaSlicePressure", "className": "FactorEmaSlicePressure", "indexTradingUnderlying": [0],
             "indexFactorUnderlying": [], "paraNumOrderMax": 5, "paraNumOrderMin": 1, "paraEmaSlicePressureLag": 1,
             "save": true},

            {"name": "factorAveAmplitude", "className": "FactorAveAmplitude", "indexTradingUnderlying": [0],
             "indexFactorUnderlying": [], "paraAmplitudeLag": 5, "paraFastLag": 10, "paraSlowLag": 20, "save": true},

            {"name": "factorOrderPressure", "className": "FactorOrderPressure", "indexTradingUnderlying": [0],
             "indexFactorUnderlying": [], "paraOrderPressureLag": 1, "save": true},

            {"name": "factorEmaOrderPressureBuy", "className": "FactorEmaOrderPressureBuy",
             "indexTradingUnderlying": [0],
             "indexFactorUnderlying": [], "paraOrderPressureLag": 1, "save": true},

            {"name": "factorEmaOrderPressureSell", "className": "FactorEmaOrderPressureSell",
             "indexTradingUnderlying": [0],
             "indexFactorUnderlying": [], "paraOrderPressureLag": 1, "save": true},

            {"name": "factorEmaBidHugeOrderMultiple1", "className": "FactorEmaBidHugeOrderMultiple",
             "indexTradingUnderlying": [0], "indexFactorUnderlying": [],
             "paraLag": 1, "paraNumOrderMax": 3, "paraNumOrderMin": 1, "paraNumOrderMaxForAveOrderVolume": 10,
             "paraNumOrderMinForAveOrderVolume": 1, "paraEmaAveOrderVolumeLag": null, "save": true},

            {"name": "factorEmaAskHugeOrderMultiple1", "className": "FactorEmaAskHugeOrderMultiple",
             "indexTradingUnderlying": [0], "indexFactorUnderlying": [],
             "paraLag": 1, "paraNumOrderMax": 3, "paraNumOrderMin": 1, "paraNumOrderMaxForAveOrderVolume": 10,
             "paraNumOrderMinForAveOrderVolume": 1, "paraEmaAveOrderVolumeLag": null, "save": true},

            {"name": "factorEmaBidOrderBookMultiple1", "className": "FactorEmaBidOrderBookMultiple",
             "indexTradingUnderlying": [0], "indexFactorUnderlying": [],
             "paraLag": 1, "paraNumOrderMax": 3, "paraNumOrderMin": 1, "paraNumOrderMaxForAveOrderVolume": 10,
             "paraNumOrderMinForAveOrderVolume": 1, "paraEmaAveOrderVolumeLag": null, "save": true},

            {"name": "factorEmaAskOrderBookMultiple1", "className": "FactorEmaAskOrderBookMultiple",
             "indexTradingUnderlying": [0], "indexFactorUnderlying": [],
             "paraLag": 1, "paraNumOrderMax": 3, "paraNumOrderMin": 1, "paraNumOrderMaxForAveOrderVolume": 10,
             "paraNumOrderMinForAveOrderVolume": 1, "paraEmaAveOrderVolumeLag": null, "save": true},

            {"name": "factorDistanceToAvePrice", "className": "FactorDistanceToAvePrice", "indexTradingUnderlying": [0],
             "indexFactorUnderlying": [], "save": true},

            {"name": "factorDistanceToMAPrice", "className": "FactorDistanceToMAPrice", "indexTradingUnderlying": [0],
             "indexFactorUnderlying": [], "paraMALag": 120, "save": true},

            {"name": "factorDistanceToMAPrice", "className": "FactorDistanceToMAPrice", "indexTradingUnderlying": [0],
             "indexFactorUnderlying": [], "paraMALag": 60, "save": true},

            {"name": "factorMomentum", "className": "FactorMomentum",
             "indexTradingUnderlying": [0], "indexFactorUnderlying": [],
             "paraLag": 3, "paraEmaMidPriceLag": 5, "save": true},

            {"name": "factorMomentum", "className": "FactorMomentum",
             "indexTradingUnderlying": [0], "indexFactorUnderlying": [],
             "paraLag": 10, "paraEmaMidPriceLag": 5, "save": true},

            {"name": "factorEmaActiveOrder", "className": "FactorEmaActiveOrder", "indexTradingUnderlying": [0],
             "indexFactorUnderlying": [], "paraEmaActiveOrderLag": 3,
             "save": true},

            {"name": "factorDistanceToVwap", "className": "FactorDistanceToVwap", "indexTradingUnderlying": [0],
             "indexFactorUnderlying": [], "paraLag": 20, "save": true},

            {"name": "factorMaAmount", "className": "FactorMaAmount", "indexTradingUnderlying": [0],
             "indexFactorUnderlying": [], "paraLag": 2, "save": true}
        ],
    "Tag":
        {"indexTradingUnderlying": [0], "indexFactorUnderlying": [], "paraMaxDropHorizon": 0.002,
         "paraEmaMidPriceLag": 4, "paraOrderPressureLag": 4, "paraNumOrderMax": 5, "paraNumOrderMin": 1,
         "paraEmaSlicePressureLag": 8, "paraMaxLose": 0.004, "paraFastLag": 10, "paraSlowLag": 20}
}

